sync

diff --git a/whatsapp-nativefier/make b/whatsapp-nativefier/make
--- a/whatsapp-nativefier/make
+++ b/whatsapp-nativefier/make
@@ -1,5 +1,23 @@
 #!/usr/bin/env bash
 
+set -o errexit      # Exit on most errors (see the manual)
+set -o nounset      # Disallow expansion of unset variables
+set -o pipefail     # Use last non-zero exit code in a pipeline
+set -o errtrace     # Ensure the error trap handler is inherited
+
+distro_name=$(lsb_release -i | sed 's/.*:\s*//g')
+if [ "$distro_name" != "Ubuntu" ] ; then
+  echo "Package only for Ubuntu"
+  exit 1
+fi
+
+curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
+sudo apt-get install -y nodejs
+
+# install nativifier
+npm list -g nativefier || sudo npm install -g nativefier
+npm update nativefier
+
 cd git_src
 
 pkgname=whatsapp-nativefier
@@ -9,7 +27,7 @@ nativefier \
   --icon "${pkgname}.png" \
   --width "800px" \
   --height "600px" \
-  --user-agent "safari" \
+  --user-agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 12_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15" \
   --inject "${pkgname}-inject.js" \
   --browserwindow-options '{ "webPreferences": { "spellcheck": true } }' \
   --verbose \
